default: switch meta-qt5 to dunfell upstream branch
we currently use upstream master branch for meta-qt5, because at the
time the manifest was created, we had an issue preventing us to use the
dunfell branch (cannot remember the exact reason).

today, we encounter the following build error:

[20:05:36.889048] | /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/client/qwaylandinputcontext.cpp: In member function 'virtual void QtWaylandClient::QWaylandInputContext::reset()':
[20:05:36.889081] | /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/client/qwaylandinputcontext.cpp:410:9: error: 'm_composeState' was not declared in this scope
[20:05:36.889109] |   410 |     if (m_composeState)
[20:05:36.889135] |       |         ^~~~~~~~~~~~~~
[20:05:36.889162] | compiling /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/client/hardwareintegration/qwaylandhardwareintegration.cpp
[20:05:36.889189] | /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/client/qwaylandinputcontext.cpp:411:9: error: 'xkb_compose_state_reset' was not declared in this scope
[20:05:36.889215] |   411 |         xkb_compose_state_reset(m_composeState);
[20:05:36.889244] |       |         ^~~~~~~~~~~~~~~~~~~~~~~
[20:05:36.889273] | Wayland server header /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/extensions/qt-key-unstable-v1.xml
[20:05:36.889303] | compiling /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/compositor/compositor_api/qwaylandkeymap.cpp
[20:05:36.889331] | compiling /home/builder/workspace/build/tmp/work/aarch64-poky-linux/qtwayland/5.15.4+gitAUTOINC+f1e6c8764d-r0/git/src/client/shellintegration/qwaylandshellintegrationfactory.cpp
[20:05:36.889359] | Makefile:1777: recipe for target '.obj/qwaylandinputcontext.o' failed

this error is introduced by the upgrade to v5.15.4-lts-lgpl
(https://github.com/meta-qt5/meta-qt5/commit/7cf45cf69dc2013a13b4beb2d84370c2330e4441)
most likely because the rest of our packages are still on dunfell.

So switch back to dunfell upstream branch

Issue: AIOT-1113

Signed-off-by: Julien STEPHAN <jstephan@baylibre.com>