Revert "bootloaders: update mbedtls version"
With recent version of mbedtls 2.28.1 we have the following build
errors when we build bootloaders in secure mode:
...
aarch64-none-linux-gnu-ld.bfd: /home/julien/Documents/Baylibre/mediatek/hero/bootloaders/arm-trusted-firmware/build/mt8365/release/lib/libmbedtls.a(bignum.o): in function `mpi_montmul':
bignum.c:(.text.mpi_montmul+0xd4): undefined reference to `mbedtls_ct_mpi_uint_cond_assign'
aarch64-none-linux-gnu-ld.bfd: /home/julien/Documents/Baylibre/mediatek/hero/bootloaders/arm-trusted-firmware/build/mt8365/release/lib/libmbedtls.a(bignum.o): in function `mbedtls_mpi_exp_mod':
bignum.c:(.text.mbedtls_mpi_exp_mod+0x418): undefined reference to `mbedtls_ct_size_bool_eq'
aarch64-none-linux-gnu-ld.bfd: bignum.c:(.text.mbedtls_mpi_exp_mod+0x42c): undefined reference to `mbedtls_mpi_safe_cond_assign'
make: *** [Makefile:1236: /home/julien/Documents/Baylibre/mediatek/hero/bootloaders/arm-trusted-firmware/build/mt8365/release/bl2/bl2.elf] Error 1

Let's revert this commit and keep latest known good build tag.

This reverts commit 1fb75dbfdb1896c0daa6c11ad381aa70a26e77a3.