remotes: github: use https:// in instead of git://
According to [1], GitHub is deprecating the usage of the git:// protocol
for cloning.

We can observe this during repo sync:

> meta-qt5/meta-qt5:
> fatal: remote error:
>   The unauthenticated git protocol on port 9418 is no longer supported.
> Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
> error: Cannot fetch meta-qt5/meta-qt5 from git://github.com/meta-qt5/meta-qt5

Fix it by switching to https

[1] https://github.blog/2021-09-01-improving-git-protocol-security-github/
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>